### ISSUE TITLE
H6 ontwerpen

### ISSUE THREAD

**Issue by mstruiksma** [hugoquene/KMS-NL#16]
Er kwam een vraag van een student of er in dit hoofdstuk niet bij elk design ook een R moet staan, omdat de groepen random gekozen worden.

**Comment by hugoquene** [comment]
Goed idee, voor de designs met meer dan één groep dan. Het lijkt me ook niet veel werk...
NB note to self: het gaat om random assignment naar groepen, niet om random selectie van steekproef uit populatie!

**Comment by hugoquene** [comment]
NL H06 and EN Ch06 revised accordingly. Issue closed.
