### ISSUE TITLE
ANOVA en interactie

### ISSUE THREAD

**Issue by mstruiksma** [hugoquene/KMS-NL#17]
Kan de uitwerking van de interactie (pairwise comparisons bijv) opgenomen worden voor de ANOVA. Dit is wel voor de éénweg gedaan, maar nog niet voor de interactie in de meerweg ANOVA.

**Comment by hugoquene** [comment]
Dit is nog een open issue. Staat op de rol voor 21-22 december 2021 ;-)

**Comment by mstruiksma** [comment]
Super fijn! Ik kwam hem tegen in mijn lijstje en bedacht me dat ik daar mooi en issue van kon maken.
Tot binnenkort,
Marijn
________________________________

**Comment by hugoquene** [comment]
De tekst van §15.4 is aangepast in de KMS-NL versie (medio januari 2021). 
Daarbij ontstond issue in Table of Contents, dit is inmiddels ook opgelost. 
Het probleem was dat de ref labels {ch:inleiding} vertaald werden naar bestandsnamen en hyperlinks, die (mogelijk in interactie met update van MacBook naar OSX 12.1 Monterey) niet meer goed werkten vanwege de dubbele punt in de bestandsnaam. De oplossing was om in de crossrefs (labels en refs) de string "ch:" te vervangen door "ch-", en dat dan in alle .Rmd bestanden. 
In de repo staan nog wel obsolete bestanden docs/ch:*.html, deze worden om onduidelijke redenen toch nog aangemaakt bij het in elkaar zetten van het gitbook.
